# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetUserSettings
      directives:
        description: Enable self-elevation in WinGet Configuration
      settings:
        Settings:
          experimentalFeatures:
            configureSelfElevate: true
        Action: Partial
